// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRLXwlOR3NThFqqi1KqzORUFimt5ngOf0',
    appId: '1:639567467813:web:437f189e0df405e4e7b6cc',
    messagingSenderId: '639567467813',
    projectId: 'the-review-corner',
    authDomain: 'the-review-corner.firebaseapp.com',
    storageBucket: 'the-review-corner.appspot.com',
    measurementId: 'G-MEL1Z69T4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0NTs3tl0qmSc9mcwplye6zzC1QnrMoGQ',
    appId: '1:639567467813:android:420971297b251ec0e7b6cc',
    messagingSenderId: '639567467813',
    projectId: 'the-review-corner',
    storageBucket: 'the-review-corner.appspot.com',
  );
}
